{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "devops-shop.fullname" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "devops-shop.name" . }}
  endpoints:
    - port: http
      path: /metrics
{{- end }}
