name: CI

on:
  # pull_request:
  #   branches: [main]
  # push:
  #   branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Unit/API tests
        run: npm test

      - name: Application build
        run: npm run build

  docker:
    name: Docker Build & Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      security-events: write

    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.14.0'

      # -------------------------
      # Filesystem Security Scan
      # -------------------------

      - name: Trivy file scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          severity: 'HIGH,CRITICAL'
          output: 'trivy-fs-results.sarif'
          exit-code: '0'

      - name: Upload Filesystem SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-fs-results.sarif'
          category: 'trivy-fs-scan'

      # -------------------------
      # AWS OIDC
      # -------------------------

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Test AWS OIDC
        run: |
          aws sts get-caller-identity

      # -------------------------
      # ECR Login
      # -------------------------

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # -------------------------
      # Docker Build
      # -------------------------

      - name: Build Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: devops-shop
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            .

      # -------------------------
      # Trivy Image Scan
      # -------------------------

      - name: Trivy image scan
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: devops-shop
          IMAGE_TAG: ${{ github.sha }}
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'image'
          image-ref: '${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}'
          format: 'sarif'
          severity: 'HIGH,CRITICAL'
          output: 'trivy-image-results.sarif'
          exit-code: '0'

      - name: Upload Image SARIF to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-image-results.sarif'
          category: 'trivy-image-scan'

      # -------------------------
      # Push to ECR
      # -------------------------

      - name: Push Image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: devops-shop
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # -------------------------
      # EKS
      # -------------------------

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name ${{ secrets.EKS_CLUSTER_NAME }} \
            --region ${{ secrets.AWS_REGION }}

      - name: Test EKS Access
        run: |
          kubectl get nodes
          kubectl get pods -A

      # -------------------------
      # Deploy
      # -------------------------

      - name: Deploy to EKS using Helm
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: devops-shop
          IMAGE_TAG: ${{ github.sha }}
          HELM_RELEASE_NAME: devops-shop-release
          HELM_CHART_PATH: ./helm/devops-shop

        run: |
          helm upgrade --install $HELM_RELEASE_NAME $HELM_CHART_PATH \
            --namespace default \
            --set image.repository=$ECR_REGISTRY/$ECR_REPOSITORY \
            --set image.tag=$IMAGE_TAG \
            --wait \
            --atomic \
            --timeout 5m